name: Build Godot Game

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GODOT_VERSION: ${{ vars.GODOT_VERSION }}
  EXPORT_NAME: ${{ vars.GAME_NAME }}
  PROJECT_PATH: ${{ vars.PROJECT_PATH }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [windows, linux]

    container:
      image: barichello/godot-ci:${{ vars.GODOT_VERSION }}
      options: --memory=6g

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Setup export templates
      run: |
        wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_mono_export_templates.tpz -O templates.tpz
        mkdir -p ~/.local/share/godot/templates/${GODOT_VERSION}.stable/
        tar -xf template.tpz -C ~/.local/share/godot/templates/${GODOT_VERSION}.stable/

    - name: Build project
      run: |
        mkdir -p build/${{ matrix.platform }}
        cd ${{ env.PROJECT_PATH }}
        if [ "${{ matrix.platform }}" = "windows" ]; then
          godot --headless --verbose --export-release "Windows Desktop" "../build/windows/${{ env.EXPORT_NAME }}.exe"
        else
          godot --headless --verbose --export-release "Linux" "../build/linux/${{ env.EXPORT_NAME }}.x86_64"
        fi

    - name: Upload ${{ matrix.platform }} artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}-build
        path: build/${{ matrix.platform }}
